name: se7ty
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  easy_localization: ^3.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  go_router: ^16.2.5
  google_nav_bar: ^5.0.7
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/loading.json
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translation/ar.json
    - assets/translation/en.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
